### PR TITLE
Update home & build

### PR DESCRIPTION
**Pull request by prisae**
Update repo for:
- the move from `prisae` to the `emsig`-org;
- the build from `distutils` to `meson` (thanks @jokva).

### CODE REVIEW

**Comment by prisae** [comment]
This doesn't not work currently on many fronts.
- Version number - try setuptools_scm again with the new build backend!
- Tests
- Wrapper itself
- Deploy

**Comment by prisae** [comment]
The current setup fails, if you call `fftlog` from within the `fftlog` directory (which is the case for the tests with pytest).

EOD - need to come back on another day.

**Comment by jokva** [comment]
I pushed a patch which fixes a part of that issue by simply removing the fftlog/ dir, just doing src/ directly.

**Comment by jokva** [comment]
With these patches I see the same test failure in the CI job as I do locally. I figure you're more familiar with the API and can work on that for a bit.

**Comment by prisae** [comment]
Thanks, much appreciated! That is also the one I had locally. If I remember right, `wsave` is a "working array" in Fortran that stores all sort of things, which was not needed in the Python version, respectively constructed internally and the user did not have to bother about it. I'll have to dig in to try and remember, will do that over the holidays.

**Comment by prisae** [comment]
The current error is
```
E       TypeError: _fftlog.fhti() missing required argument 'wsave' (pos 7)
```
Something must have changed in `f2py`, but I cannot figure out what right now. Nothing changed in the signature file (although I tried adding `hide` to the `intent(out)`, but with the same error).

**Pull request merged**
